import pandas as pd
df = pd.read_excel("sugar_cosmetics.xlsx")
print("Top 5 rows:")
print(df.head())
print("\nLast 5 rows:")
print(df.tail())
print("\nDataset Info:")
print(df.info())
print("\nColumns:")
print(df.columns)
print("\nShape:")
print(df.shape)
print("\nDescribe:")
print(df.describe())
print("\nMaximum values:")
print(df.max(numeric_only=True))
print("\nMean values:")
print(df.mean(numeric_only=True))
print("Highest Likes:", df["Likes"].max())
print("Average Likes:", df["Likes"].mean())
print("\nTop 5 posts with highest likes:")
print(df.sort_values(by="Likes", ascending=False).head())