import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original Array:")
print(arr)
reshaped_arr = arr.reshape(2, 3)
print("\nReshaped Array:")
print(reshaped_arr)
flattened_arr = reshaped_arr.flatten()
print("\nFlattened Array:")
print(flattened_arr)