name = input("Enter your full name: ")
name = name.strip()
name = name.lower()
name = name.capitalize()
name = name.upper()
name = name.lstrip()
username = name.replace(" ", "madhavi")
print(name.title())
print(name * 3)
print("Formatted Username:", username)