marks = [60, 70, 80, 90, 95]
print("marks", marks)
total = sum(marks)
print("total marks is", total)
print("value at index -1 is", marks[-1])
print("value at index 0 is", marks[0])
marks[2] = 96
print("updated marks are", marks)
marks.append(33)
print(marks)
marks.insert(4,67)
print(marks)
marks.remove(60)
print(marks)
marks.pop(0)
print(marks)
marks.sort()
print(marks)
marks.reverse()
print(marks)