courses = ("btech", "bca", "bba")
print(courses)
details = ("xyz", 20, "feamle")
print(details)
salary = (50000, 20000, 15000)
print(salary)
branches = ("cse", "it", "ds", "aiml", "cs")
print(branches)
names = ("rahul", "sonu", "monu", "golu")
print(names)