p_id = int(input("enter the product id"))
p_name =input("enter the product name")
p_price =float(input("enter price of the product"))
p_rating =float(input("rate the product out of 5"))
productis_available =(input("whether the prduct is available or not")) 
print("The id of product is", (p_id))
print("The name of productt is", (p_name))
print("The price of productt is", (p_price))
print("The rating of productt is", (p_rating))
print("The availability of product is", (productis_available))