name = input("enter the name")
roll_number = int(input("enter the roll number"))
class_name = input("enter your class in character")
college = input("enter the name of your college")
fees = float(input("enter the fees of your college"))
address = input("enter your address") 
print("The name of student is",(name))
print("The roll number of student is",(roll_number))
print("The class of student is",(class_name))
print("The college of student is",(college))
print("The fees of student is",(fees))
print("The address of student is",(address))